[algokit]
min_version = "v2.0.0"

[project]
type = 'workspace'
projects_root_path = 'projects'

[project.run]
build = ['Task-7-Complete_Application-contracts', 'Task-7-Complete_Application-frontend']
